name: Gitbook

on:
  push:
    branches:
      - master
    paths:
      - 'gitbook/**'
      - '.github/workflows/gitbook.yml'
      - 'package.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install
        run: yarn install --silent --frozen-lockfile

      - name: Build Gitbook
        run: yarn gitbook build

      - name: Publish on Github Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: _book/
